[package]
name = "wowo_launchpad"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v4.0.1" }